### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by domenic** [YuzuJS/WinningJS#11]
`WinningJS/lib/resources` module has two methods:
- `augmentGetString()`: adds `{^/Other/Resource}` reference-replacement to `WinJS.Resources.getString`.
- `s(key)` which is an alias for `WinJS.Resources.getString`, so others can do `var s = require("WinningJS/lib/resources").s`

Be sure to write tests for recursive replacement of resources, i.e. `/Resource/1` is `"stuff {^/Resource/2}"` where `/Resource/2` is `"more stuff {^/Resource/3}"` and `/Resource/3` is `"even more"`. Then `s("/Resource/1")` should return `"stuff more stuff even more"`.

**Comment by pbouzakis** [comment]
See scholar's "infrastructure/StringsLoader.js" recursivelyReplaceReferences function for the string replacement logic we used in scholar.

**Comment by domenic** [comment]
Closed by 76e57e21af72e0b5c04f57876dbe01c21c4f19db
